### ISSUE TITLE
Installing cd-hit on HPC w/out 'sudo' privilege

### ISSUE THREAD

**Issue by collinstorlie** [esteinig/dartqc#1]
Attempting to install DartQC on the JCU HPC, where users lack 'sudo' privilege (needed for cd-hit).  I've followed the instructions from the URL below:

https://github.com/weizhongli/cdhit/blob/master/doc/cdhit-user-guide.wiki

Which are listed here...

* download current CD-HIT at [[https://github.com/weizhongli/cdhit/releases]], for example cd-hit-v4.6.2-2015-0511.tar.gz
  * unpack the file with " tar xvf cd-hit-v4.6.2-2015-0511.tar.gz --gunzip"
  * change dir by "cd cd-hit-v4.6.2-2015-0511"
  * compile the programs by "make" with multi-threading (default), or by "make openmp=no" without multi-threading (on old systems without OpenMP)
  * cd cd-hit-auxtools
  * compile cd-hit-auxtools by "make"

...To install cd-hit from the tar.gz file hosted on GitHub, by unzipping and then 'making'.  Unfortunately, this seems to not work.

We've insured that python is install properly and anaconda3 is added to the path before trying to run cdhit-est.  No errors are produced, and the only warning is 'cdhit-est' "command not found".

Any thoughts?

**Comment by esteinig** [comment]
Hey Collin,

had the same question from Lorenzo yesterday. 

There is an easy way around all this, will send you my response.

Briefly:

```
conda create -n dartqc -c bioconda python=3.5

source activate dartqc
conda install -c bioconda cd-hit
conda install biopython

git clone https://github.com/esteinig/dartQC

chmod +x ./dartQC/dart_qc.py

# cdhit exec installs as 'cd-hit'
./dartQC/dart_qc.py [options] --cdhit cd-hit

source deactivate
```
Not too smooth but should work, let me know.

**Comment by MboiTui** [comment]
Hello both,


Collin, attached you can find the instructions Eike gave me last week [dartQC_HPC.docx].


Those should work for the github version [dart_qc.py script].


Ideally, for Adriana's (honours student) project, it would be best if she could use the pipeline in the attached .py document [Dart_qc_GenoSilencing.py], but as highlighted in eike's instructions that would require a few extra steps.


There's a PhD student [Rodrigo Gurdek, Lynne Var Her Weiden student] that needs to use dartQC as well, and the HPC would be the best solution for him as well (both Adriana and Rodrigo have windows laptops with limited memory for a virtual machine to work smoothly).


I know it is a painful process, and that the two of you have limited time, but it would be very helpful for all research students doing genomic work to be able to access dartQC through the HPC, thus let me know if we can make it happen and what I can do to help.


Cheers,


Lorenzo




--------------------------------------------------------------------------


Lorenzo Vincenzo Bertola

Mobile: +61 405 615 394

Email: lorenzo.bertola@my.jcu.edu.au


Research Assistant @ Adaptation Laboratory

College of Science & Engineering

1st Floor Building 28 (DB28-129)

James Cook University, Townsville, QLD, 4811


Mentor @ Molecular Ecology & Evolution Laboratory

College of Science & Engineering

3rd Floor ATSIP Building (DB145-317)

James Cook University, Townsville, QLD, 4811


--------------------------------------------------------------------------------------------


________________________________

**Comment by esteinig** [comment]
I think there is enough interest in DArT data to develop the pipeline and make it properly accessible to everyone on Zodiac. Let me talk to Kyall about it. For now, easiest solution for setup on the HPC is to follow the outline above. It's good practice to have separate environments for dependencies in any case, but ultimately we should think about adding the program to `conda` or `pip` for installation. Lorenzo, do the instructions work for you?

**Comment by MboiTui** [comment]
Hey Eike,


Haven't tried it yet. Will give it a go tonight and let you know.


I still have limited knowledge/understanding of this area, but if I can help to make the pipeline accessible through Zodiac, let me know!


Cheers,


Lorenzo




--------------------------------------------------------------------------


Lorenzo Vincenzo Bertola

Mobile: +61 405 615 394

Email: lorenzo.bertola@my.jcu.edu.au


Research Assistant @ Adaptation Laboratory

College of Science & Engineering

1st Floor Building 28 (DB28-129)

James Cook University, Townsville, QLD, 4811


Mentor @ Molecular Ecology & Evolution Laboratory

College of Science & Engineering

3rd Floor ATSIP Building (DB145-317)

James Cook University, Townsville, QLD, 4811


--------------------------------------------------------------------------------------------


________________________________

**Comment by esteinig** [comment]
Thanks mate, appreciate it!

**Comment by cbajema** [comment]
Hi All,

I've added instructions for installing directly onto Windows without a virtual machine (in workshop.md) if this helps anyone.

**Comment by MboiTui** [comment]
Hi everyone,

I finally remembered to add instructions to install dartQC on mac. 

I'm pretty new to bash, so feel free to suggest any corrections to make it more fluent and accurate and less redundant.

Cheers,
L.B.

**Comment by esteinig** [comment]
Hey just to give you a heads up, I am restructuring the program at the moment and adding lots of documentation. Unfortunately, Zodiac is quite a mess to set up anything (it even still has TCSH as a default shell instead of Bash). It is therefore a bit more complicated to get it running but please let me know how you fare, super happy to get some feedback.

Best,

Eike

**Comment by esteinig** [comment]
I am going to close this issue for now as it is resolved as of v.0.1.5
