### ISSUE TITLE
Correction to flags for PREFIX

### ISSUE THREAD

**Issue by blanchedanastasi** [esteinig/dartqc#2]
Hi Eike,

I had a minor issue during installation of Conda dependencies, from a windows machine, using Putty and Filezilla:

The prefix flag needed to be changed slightly from:

bash Miniconda3-latest-Linux-x86_64.sh --prefix=$HOME/miniconda

to:
bash Miniconda3-latest-Linux-x86_64.sh -p PREFIX=$HOME/miniconda

Cheers, Blanche

**Comment by esteinig** [comment]
Sorry Blanche should have been removed entirely, have fixed now with commit a97c64b
