### ISSUE TITLE
Unable to install on HPC

### ISSUE THREAD

**Issue by blanchedanastasi** [esteinig/dartqc#3]
Hello Eike,

I am pretty inexperienced with the HPC. I have tried for about 2 hours now to get DART QC installed on the HPC, but I lack the skills to determine what the problem is.

It has become pretty urgent now for me to get this fantastic program up and running.

I was wondering if you could either guide me through the HPC installation process, or provide some really clear, step by step documentation for inexperienced users?

Thanks in advance :)

Blanche

**Comment by esteinig** [comment]
Hey Blanche,

not sure what trouble you are running into. Happy to help, but can you elaborate?

Step-by-step on Zodiac (do not enter omments flagged with #):

```
# enter bash shell
bash

# install conda, let installer append to PATH (will ask you)
wget -c https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
source ~/.bashrc

# install program
conda install -c bioconda -c esteinig dartqc

# test
dartqc --help
dartqc --version
```

**Comment by blanchedanastasi** [comment]
Thank-you. Its a silly error on my and with your input I was able to
recognise my issue, install it and run it! Thank-you!

#The issue was that if I entered this all at once, it fails:

wget -c https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
source ~/.bashrc

#If I enter:

wget -c https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh

#And then go through and answer the questions, and then put:

source ~/.bashrc

#It installs.

I have attached an R script for beginners with the details you
provided, some of my explanatory notes, and appended your
documentation for use:

Thanks again Eike!


*Have a great day!*


*Warm regards,*

*Blanche D'Anastasi  *
*PhD Candidate*
*Sea snake ecology and conservation genomics*
*Molecular Ecology and Evolutionary Laboratory*

*College of Science and Engineering
<https://www.jcu.edu.au/college-of-science-and-engineering>*

*AIMS@JCU <http://aims.jcu.edu.au/>*

*Layne Beachley Aim for the Stars Scholarship recipient
**https://www.aimforthestars.com.au/
<https://www.aimforthestars.com.au/>*
*Director, Deadly Science Getaway *
*http://www.abc.net.au/news/2016-11-07/deadly-science-getaway-inspires-indigenous-careers/7988292*
<http://www.abc.net.au/news/2016-11-07/deadly-science-getaway-inspires-indigenous-careers/7988292>
*
<http://www.abc.net.au/news/2016-11-07/deadly-science-getaway-inspires-indigenous-careers/7988292>
Deadly
science: Island getaway inspires Indigenous girls ...
<http://www.abc.net.au/news/2016-11-07/deadly-science-getaway-inspires-indigenous-careers/7988292>www.abc.net.au
<http://www.abc.net.au>The Deadly Science Getaway aims to improve career
options for young women from Indigenous communities in north Queensland.*
*Phone (M):*  0439 89 66 97
*Office: *07 4781 5441
*Email:* blanche.danastasi@gmail.com
*Address:* ATSIP Office 319H, Level 3, Building 145, James Cook
University, Townsville, Q, 4811
*Facebook group:* Australian Sea Snakes
https://www.facebook.com/groups/769160779847732/
*Twitter: *#SeaSnakeBlanche
*Web page: *www.coralcoe.org.au/students/blanche-danastasi-3

I acknowledge the Wulgurukaba and Bindal people as the Traditional Owners
of the land I work on.

><(((o> Let yourself be silently drawn by the strange pull of what you
really love. It will not lead you astray. Rumi <o)))><

NOTICE - This e-mail and any attachments are confidential and only for the
use of the addressee. If you have received this e-mail in error, you are
strictly prohibited from using, forwarding, printing, copying or dealing in
anyway whatsoever with it, and are requested to reply immediately by e-mail
to the sender and delete the email.
